---

# Main tasks file for hadoop role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::hadoop'
    - 'role::hadoop::init'
